# Generated by Django 4.2 on 2023-04-21 21:41

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_suitable_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stone',
            name='birth_month_stone',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'farvardin'), ('2', 'ordibehesht'), ('3', 'khordad'), ('4', 'tir'), ('5', 'mordad'), ('6', 'shahrivar'), ('7', 'mehr'), ('8', 'aban'), ('9', 'azar'), ('10', 'dey'), ('11', 'bahman'), ('12', 'esfand')], max_length=5, verbose_name='birth month stone'),
        ),
    ]
