# Generated by Django 4.2 on 2023-04-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_stone_birth_month_stone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Product_inventory',
            field=models.PositiveIntegerField(verbose_name='Product inventory'),
        ),
    ]
