# Generated by Django 4.2 on 2023-04-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_product_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='suitable_for',
            field=models.CharField(choices=[('M', 'Men'), ('women', 'Women'), ('B', 'Men and Women')], max_length=10, verbose_name='suitable for'),
        ),
    ]
