# Generated by Django 4.2 on 2023-04-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_suitable_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='suitable_for',
            field=models.CharField(choices=[('Men', 'Men'), ('women', 'Women'), ('Men and Women', 'Men and Women')], max_length=13, verbose_name='suitable for'),
        ),
    ]
