# Generated by Django 4.2 on 2023-04-23 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_product_suitable_for'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Product_inventory',
            new_name='product_inventory',
        ),
    ]
