# Generated by Django 4.2 on 2023-04-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_rename_product_inventory_product_product_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_material',
            field=models.CharField(choices=[('Natural Stone', 'Natural Stone'), ('Artificial Stone', 'Artificial Stone')], max_length=16, verbose_name='product material'),
        ),
        migrations.AlterField(
            model_name='stone',
            name='stone_quality',
            field=models.CharField(choices=[('Gemstone', 'Gemstone'), ('Semiprecious stone', 'Semiprecious stone')], max_length=18, verbose_name='stone_quality'),
        ),
    ]
