# Generated by Django 4.2 on 2023-04-23 13:52

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_product_product_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stone',
            name='birth_month_stone',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('farvardin', 'farvardin'), ('ordibehesht', 'ordibehesht'), ('khordad', 'khordad'), ('tir', 'tir'), ('mordad', 'mordad'), ('shahrivar', 'shahrivar'), ('mehr', 'mehr'), ('aban', 'aban'), ('azar', 'azar'), ('dey', 'dey'), ('bahman', 'bahman'), ('esfand', 'esfand')], max_length=12, verbose_name='birth month stone'),
        ),
    ]
