# Generated by Django 4.2 on 2023-04-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_stone_birth_month_stone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, upload_to='product_cover/', verbose_name='product image'),
        ),
    ]
